"""initial_schema

Revision ID: bc63dc5f5f98
Revises: 
Create Date: 2026-07-11 14:01:45.820593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc63dc5f5f98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descrizione', sa.String(length=255), nullable=True),
    sa.Column('data_creazione', sa.DateTime(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_nome'), ['nome'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descrizione', sa.String(length=255), nullable=True),
    sa.Column('data_creazione', sa.DateTime(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_nome'), ['nome'], unique=True)

    op.create_table('compatibilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descrizione', sa.String(length=255), nullable=True),
    sa.Column('data_creazione', sa.DateTime(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compatibilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compatibilities_nome'), ['nome'], unique=True)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cognome', sa.String(length=100), nullable=True),
    sa.Column('ragione_sociale', sa.String(length=140), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('codice_fiscale', sa.String(length=20), nullable=True),
    sa.Column('partita_iva', sa.String(length=20), nullable=True),
    sa.Column('indirizzo', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.Column('data_creazione', sa.DateTime(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_attivo'), ['attivo'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_codice_fiscale'), ['codice_fiscale'], unique=True)
        batch_op.create_index(batch_op.f('ix_customers_cognome'), ['cognome'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_partita_iva'), ['partita_iva'], unique=True)
        batch_op.create_index(batch_op.f('ix_customers_ragione_sociale'), ['ragione_sociale'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_telefono'), ['telefono'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('descrizione', sa.String(length=255), nullable=True),
    sa.Column('data_creazione', sa.DateTime(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_nome'), ['nome'], unique=True)

    op.create_table('shop_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chiave', sa.String(length=80), nullable=False),
    sa.Column('valore', sa.String(length=255), nullable=False),
    sa.Column('descrizione', sa.String(length=255), nullable=True),
    sa.Column('data_creazione', sa.DateTime(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shop_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_preferences_chiave'), ['chiave'], unique=True)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('indirizzo', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('data_creazione', sa.DateTime(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_nome'), ['nome'], unique=True)

    op.create_table('vat_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('aliquota', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('descrizione', sa.String(length=255), nullable=True),
    sa.Column('attiva', sa.Boolean(), nullable=False),
    sa.Column('predefinita', sa.Boolean(), nullable=False),
    sa.Column('data_creazione', sa.DateTime(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vat_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vat_rates_attiva'), ['attiva'], unique=False)
        batch_op.create_index(batch_op.f('ix_vat_rates_nome'), ['nome'], unique=True)
        batch_op.create_index(batch_op.f('ix_vat_rates_predefinita'), ['predefinita'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=140), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.Column('compatibilita_id', sa.Integer(), nullable=True),
    sa.Column('formato_confezione', sa.String(length=120), nullable=True),
    sa.Column('prezzo_acquisto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('prezzo_vendita', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantita_disponibile', sa.Integer(), nullable=False),
    sa.Column('quantita_minima_alert', sa.Integer(), nullable=False),
    sa.Column('sku_barcode', sa.String(length=80), nullable=True),
    sa.Column('fornitore_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.Column('data_creazione', sa.DateTime(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['compatibilita_id'], ['compatibilities.id'], ),
    sa.ForeignKeyConstraint(['fornitore_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['marca_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_attivo'), ['attivo'], unique=False)
        batch_op.create_index('ix_products_categoria_attivo', ['categoria_id', 'attivo'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_compatibilita_id'), ['compatibilita_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_fornitore_id'), ['fornitore_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_marca_id'), ['marca_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_nome'), ['nome'], unique=False)
        batch_op.create_index('ix_products_nome_marca', ['nome', 'marca_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_quantita_disponibile'), ['quantita_disponibile'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_sku_barcode'), ['sku_barcode'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('ruolo_id', sa.Integer(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.Column('data_creazione', sa.DateTime(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ruolo_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_attivo'), ['attivo'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_ruolo_id'), ['ruolo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.create_index('ix_users_username_email', ['username', 'email'], unique=False)

    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('azione', sa.String(length=120), nullable=False),
    sa.Column('entita_tipo', sa.String(length=60), nullable=False),
    sa.Column('entita_id', sa.String(length=60), nullable=True),
    sa.Column('dettagli', sa.Text(), nullable=True),
    sa.Column('data_ora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['utente_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index('ix_activity_logs_data_azione', ['data_ora', 'azione'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_data_ora'), ['data_ora'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_utente_id'), ['utente_id'], unique=False)

    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimento', sa.String(length=40), nullable=False),
    sa.Column('data_ora', sa.DateTime(), nullable=False),
    sa.Column('prodotto_id', sa.Integer(), nullable=False),
    sa.Column('quantita', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('costo_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('operatore_id', sa.Integer(), nullable=False),
    sa.Column('riferimento_entita', sa.String(length=80), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['operatore_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prodotto_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_movements_data_ora'), ['data_ora'], unique=False)
        batch_op.create_index('ix_inventory_movements_data_tipo', ['data_ora', 'tipo_movimento'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_operatore_id'), ['operatore_id'], unique=False)
        batch_op.create_index('ix_inventory_movements_prodotto', ['prodotto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_riferimento_entita'), ['riferimento_entita'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_tipo_movimento'), ['tipo_movimento'], unique=False)

    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_ora', sa.DateTime(), nullable=False),
    sa.Column('totale_lordo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sconto_tipo', sa.String(length=20), nullable=False),
    sa.Column('sconto_valore', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('totale_netto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pagamento', sa.String(length=30), nullable=False),
    sa.Column('note_cliente', sa.String(length=255), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('vat_rate_id', sa.Integer(), nullable=True),
    sa.Column('aliquota_iva_snapshot', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('totale_iva', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('operatore_id', sa.Integer(), nullable=False),
    sa.Column('stato', sa.String(length=20), nullable=False),
    sa.Column('margine_stimato', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['operatore_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vat_rate_id'], ['vat_rates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_data_ora'), ['data_ora'], unique=False)
        batch_op.create_index('ix_sales_data_ora_stato', ['data_ora', 'stato'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_operatore_id'), ['operatore_id'], unique=False)
        batch_op.create_index('ix_sales_pagamento', ['metodo_pagamento'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_stato'), ['stato'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_vat_rate_id'), ['vat_rate_id'], unique=False)

    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendita_id', sa.Integer(), nullable=False),
    sa.Column('prodotto_id', sa.Integer(), nullable=False),
    sa.Column('quantita', sa.Integer(), nullable=False),
    sa.Column('prezzo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotale', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_unitario_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('margine_riga', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['prodotto_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['vendita_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_items_prodotto_id'), ['prodotto_id'], unique=False)
        batch_op.create_index('ix_sale_items_sale_prodotto', ['vendita_id', 'prodotto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_items_vendita_id'), ['vendita_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_items_vendita_id'))
        batch_op.drop_index('ix_sale_items_sale_prodotto')
        batch_op.drop_index(batch_op.f('ix_sale_items_prodotto_id'))

    op.drop_table('sale_items')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_vat_rate_id'))
        batch_op.drop_index(batch_op.f('ix_sales_stato'))
        batch_op.drop_index('ix_sales_pagamento')
        batch_op.drop_index(batch_op.f('ix_sales_operatore_id'))
        batch_op.drop_index('ix_sales_data_ora_stato')
        batch_op.drop_index(batch_op.f('ix_sales_data_ora'))
        batch_op.drop_index(batch_op.f('ix_sales_customer_id'))

    op.drop_table('sales')
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_movements_tipo_movimento'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_riferimento_entita'))
        batch_op.drop_index('ix_inventory_movements_prodotto')
        batch_op.drop_index(batch_op.f('ix_inventory_movements_operatore_id'))
        batch_op.drop_index('ix_inventory_movements_data_tipo')
        batch_op.drop_index(batch_op.f('ix_inventory_movements_data_ora'))

    op.drop_table('inventory_movements')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_utente_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_data_ora'))
        batch_op.drop_index('ix_activity_logs_data_azione')

    op.drop_table('activity_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_username_email')
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_ruolo_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_attivo'))

    op.drop_table('users')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_sku_barcode'))
        batch_op.drop_index(batch_op.f('ix_products_quantita_disponibile'))
        batch_op.drop_index('ix_products_nome_marca')
        batch_op.drop_index(batch_op.f('ix_products_nome'))
        batch_op.drop_index(batch_op.f('ix_products_marca_id'))
        batch_op.drop_index(batch_op.f('ix_products_fornitore_id'))
        batch_op.drop_index(batch_op.f('ix_products_compatibilita_id'))
        batch_op.drop_index(batch_op.f('ix_products_categoria_id'))
        batch_op.drop_index('ix_products_categoria_attivo')
        batch_op.drop_index(batch_op.f('ix_products_attivo'))

    op.drop_table('products')
    with op.batch_alter_table('vat_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vat_rates_predefinita'))
        batch_op.drop_index(batch_op.f('ix_vat_rates_nome'))
        batch_op.drop_index(batch_op.f('ix_vat_rates_attiva'))

    op.drop_table('vat_rates')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_nome'))

    op.drop_table('suppliers')
    with op.batch_alter_table('shop_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_preferences_chiave'))

    op.drop_table('shop_preferences')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_nome'))

    op.drop_table('roles')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_telefono'))
        batch_op.drop_index(batch_op.f('ix_customers_ragione_sociale'))
        batch_op.drop_index(batch_op.f('ix_customers_partita_iva'))
        batch_op.drop_index(batch_op.f('ix_customers_nome'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))
        batch_op.drop_index(batch_op.f('ix_customers_cognome'))
        batch_op.drop_index(batch_op.f('ix_customers_codice_fiscale'))
        batch_op.drop_index(batch_op.f('ix_customers_attivo'))

    op.drop_table('customers')
    with op.batch_alter_table('compatibilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compatibilities_nome'))

    op.drop_table('compatibilities')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_nome'))

    op.drop_table('categories')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_nome'))

    op.drop_table('brands')
    # ### end Alembic commands ###
